package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0



/**
 * Acesso generated by hbm2java
 */
public class Acesso  implements java.io.Serializable {


     private int codigo;

    public Acesso() {
    }

    public Acesso(int codigo) {
       this.codigo = codigo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }




}


