package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private double salario;
     private Set pessoas = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(int codigo) {
        this.codigo = codigo;
    }
    public Cargo(int codigo, String nome, double salario, Set pessoas) {
       this.codigo = codigo;
       this.nome = nome;
       this.salario = salario;
       this.pessoas = pessoas;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


