package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Conta generated by hbm2java
 */
public class Conta  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private Date data;
     private String situacao;

    public Conta() {
    }

	
    public Conta(int codigo) {
        this.codigo = codigo;
    }
    public Conta(int codigo, String nome, Date data, String situacao) {
       this.codigo = codigo;
       this.nome = nome;
       this.data = data;
       this.situacao = situacao;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }




}


