package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int codigo;
     private String cnpj;
     private String razaosocial;
     private String fantasia;
     private Date abertura;
     private String smtp;
     private String pop3;
     private String email;
     private String senha;
     private int portasmtp;
     private int portapop3;
     private String tipo;

    public Empresa() {
    }

	
    public Empresa(int codigo, String tipo) {
        this.codigo = codigo;
        this.tipo = tipo;
    }
    public Empresa(int codigo, String cnpj, String razaosocial, String fantasia, Date abertura, String smtp, String pop3, String email, String senha, int portasmtp, int portapop3, String tipo) {
       this.codigo = codigo;
       this.cnpj = cnpj;
       this.razaosocial = razaosocial;
       this.fantasia = fantasia;
       this.abertura = abertura;
       this.smtp = smtp;
       this.pop3 = pop3;
       this.email = email;
       this.senha = senha;
       this.portasmtp = portasmtp;
       this.portapop3 = portapop3;
       this.tipo = tipo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getRazaosocial() {
        return this.razaosocial;
    }
    
    public void setRazaosocial(String razaosocial) {
        this.razaosocial = razaosocial;
    }
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }
    public Date getAbertura() {
        return this.abertura;
    }
    
    public void setAbertura(Date abertura) {
        this.abertura = abertura;
    }
    public String getSmtp() {
        return this.smtp;
    }
    
    public void setSmtp(String smtp) {
        this.smtp = smtp;
    }
    public String getPop3() {
        return this.pop3;
    }
    
    public void setPop3(String pop3) {
        this.pop3 = pop3;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getPortasmtp() {
        return this.portasmtp;
    }
    
    public void setPortasmtp(int portasmtp) {
        this.portasmtp = portasmtp;
    }
    public int getPortapop3() {
        return this.portapop3;
    }
    
    public void setPortapop3(int portapop3) {
        this.portapop3 = portapop3;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


