package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0



/**
 * Formapagamento generated by hbm2java
 */
public class Formapagamento  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private double taxa;

    public Formapagamento() {
    }

	
    public Formapagamento(int codigo) {
        this.codigo = codigo;
    }
    public Formapagamento(int codigo, String nome, double taxa) {
       this.codigo = codigo;
       this.nome = nome;
       this.taxa = taxa;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public double getTaxa() {
        return this.taxa;
    }
    
    public void setTaxa(double taxa) {
        this.taxa = taxa;
    }




}


