package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0



/**
 * Ftp generated by hbm2java
 */
public class Ftp  implements java.io.Serializable {


     private int codigo;
     private String host;
     private String banco;
     private String usuario;
     private String senha;
     private String diretorio;

    public Ftp() {
    }

	
    public Ftp(int codigo) {
        this.codigo = codigo;
    }
    public Ftp(int codigo, String host, String banco, String usuario, String senha, String diretorio) {
       this.codigo = codigo;
       this.host = host;
       this.banco = banco;
       this.usuario = usuario;
       this.senha = senha;
       this.diretorio = diretorio;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getDiretorio() {
        return this.diretorio;
    }
    
    public void setDiretorio(String diretorio) {
        this.diretorio = diretorio;
    }




}


