package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0



/**
 * Imposto generated by hbm2java
 */
public class Imposto  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String lei;
     private double porcentagem;

    public Imposto() {
    }

	
    public Imposto(int codigo) {
        this.codigo = codigo;
    }
    public Imposto(int codigo, String nome, String lei, double porcentagem) {
       this.codigo = codigo;
       this.nome = nome;
       this.lei = lei;
       this.porcentagem = porcentagem;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLei() {
        return this.lei;
    }
    
    public void setLei(String lei) {
        this.lei = lei;
    }
    public double getPorcentagem() {
        return this.porcentagem;
    }
    
    public void setPorcentagem(double porcentagem) {
        this.porcentagem = porcentagem;
    }




}


