package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0



/**
 * Itenscompra generated by hbm2java
 */
public class Itenscompra  implements java.io.Serializable {


     private int codigo;
     private Produto produto;
     private Compra compra;
     private double valor;

    public Itenscompra() {
    }

	
    public Itenscompra(int codigo) {
        this.codigo = codigo;
    }
    public Itenscompra(int codigo, Produto produto, Compra compra, double valor) {
       this.codigo = codigo;
       this.produto = produto;
       this.compra = compra;
       this.valor = valor;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }




}


