package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private int codigo;
     private Cargo cargo;
     private Date nascimento;
     private String telefone;
     private String nome;
     private String cpf;
     private String rg;
     private String login;
     private String senha;
     private String email;
     private String pai;
     private String mae;
     private String tipologradouro;
     private String logradouro;
     private String bairro;
     private String cidade;
     private String estado;
     private String cep;
     private String celular;
     private String complemento;
     private String num;
     private Set compras = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Set vendas_1 = new HashSet(0);
     private Set compras_1 = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(int codigo) {
        this.codigo = codigo;
    }
    public Pessoa(int codigo, Cargo cargo, Date nascimento, String telefone, String nome, String cpf, String rg, String login, String senha, String email, String pai, String mae, String tipologradouro, String logradouro, String bairro, String cidade, String estado, String cep, String celular, String complemento, String num, Set compras, Set vendas, Set vendas_1, Set compras_1) {
       this.codigo = codigo;
       this.cargo = cargo;
       this.nascimento = nascimento;
       this.telefone = telefone;
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.login = login;
       this.senha = senha;
       this.email = email;
       this.pai = pai;
       this.mae = mae;
       this.tipologradouro = tipologradouro;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.cidade = cidade;
       this.estado = estado;
       this.cep = cep;
       this.celular = celular;
       this.complemento = complemento;
       this.num = num;
       this.compras = compras;
       this.vendas = vendas;
       this.vendas_1 = vendas_1;
       this.compras_1 = compras_1;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPai() {
        return this.pai;
    }
    
    public void setPai(String pai) {
        this.pai = pai;
    }
    public String getMae() {
        return this.mae;
    }
    
    public void setMae(String mae) {
        this.mae = mae;
    }
    public String getTipologradouro() {
        return this.tipologradouro;
    }
    
    public void setTipologradouro(String tipologradouro) {
        this.tipologradouro = tipologradouro;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getVendas_1() {
        return this.vendas_1;
    }
    
    public void setVendas_1(Set vendas_1) {
        this.vendas_1 = vendas_1;
    }
    public Set getCompras_1() {
        return this.compras_1;
    }
    
    public void setCompras_1(Set compras_1) {
        this.compras_1 = compras_1;
    }




}


