package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String codigobarra;
     private double largura;
     private double comprimento;
     private double altura;
     private double peso;
     private double custo;
     private double venda;

    public Produto() {
    }

	
    public Produto(int codigo) {
        this.codigo = codigo;
    }
    public Produto(int codigo, String nome, String codigobarra, double largura, double comprimento, double altura, double peso, double custo, double venda, Set itensvendas, Set itenscompras, Set itenscompras_1, Set itensvendas_1) {
       this.codigo = codigo;
       this.nome = nome;
       this.codigobarra = codigobarra;
       this.largura = largura;
       this.comprimento = comprimento;
       this.altura = altura;
       this.peso = peso;
       this.custo = custo;
       this.venda = venda;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCodigobarra() {
        return this.codigobarra;
    }
    
    public void setCodigobarra(String codigobarra) {
        this.codigobarra = codigobarra;
    }
    public double getLargura() {
        return this.largura;
    }
    
    public void setLargura(double largura) {
        this.largura = largura;
    }
    public double getComprimento() {
        return this.comprimento;
    }
    
    public void setComprimento(double comprimento) {
        this.comprimento = comprimento;
    }
    public double getAltura() {
        return this.altura;
    }
    
    public void setAltura(double altura) {
        this.altura = altura;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public double getCusto() {
        return this.custo;
    }
    
    public void setCusto(double custo) {
        this.custo = custo;
    }
    public double getVenda() {
        return this.venda;
    }
    
    public void setVenda(double venda) {
        this.venda = venda;
    }

}


