package vo;
// Generated 30/09/2013 20:22:48 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private int codigo;
     private Pessoa pessoa;
     private Date dtvenda;
     private Date dtvencimento;
     private int parcela;
     private Set itensvendas = new HashSet(0);
     private Set itensvendas_1 = new HashSet(0);

    public Venda() {
    }

	
    public Venda(int codigo) {
        this.codigo = codigo;
    }
    public Venda(int codigo, Pessoa pessoa, Date dtvenda, Date dtvencimento, int parcela, Set itensvendas, Set itensvendas_1) {
       this.codigo = codigo;
       this.pessoa = pessoa;
       this.dtvenda = dtvenda;
       this.dtvencimento = dtvencimento;
       this.parcela = parcela;
       this.itensvendas = itensvendas;
       this.itensvendas_1 = itensvendas_1;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Date getDtvenda() {
        return this.dtvenda;
    }
    
    public void setDtvenda(Date dtvenda) {
        this.dtvenda = dtvenda;
    }
    public Date getDtvencimento() {
        return this.dtvencimento;
    }
    
    public void setDtvencimento(Date dtvencimento) {
        this.dtvencimento = dtvencimento;
    }
    public int getParcela() {
        return this.parcela;
    }
    
    public void setParcela(int parcela) {
        this.parcela = parcela;
    }
    public Set getItensvendas() {
        return this.itensvendas;
    }
    
    public void setItensvendas(Set itensvendas) {
        this.itensvendas = itensvendas;
    }
    public Set getItensvendas_1() {
        return this.itensvendas_1;
    }
    
    public void setItensvendas_1(Set itensvendas_1) {
        this.itensvendas_1 = itensvendas_1;
    }




}


