/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import static java.awt.Cursor.getPredefinedCursor;
import static java.awt.EventQueue.invokeLater;
import java.util.ArrayList;
import java.util.List;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import negocio.CargoRN;
import persistencia.Conexao;
import visao.tabelas.TableModelCargo;
import vo.Cargo;

/**
 *
 * @author ThyagoHenrique
 */
public class JFCargo extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

     CargoRN            crn;
     int                qtd       = 1;
     List<Cargo>        obj       = new ArrayList<>(qtd);
     TableModelCargo    tm        = new TableModelCargo();
     String             msg       = "";
     Cargo              cargo;
     Conexao            cx;
    /**
     * Creates new form JFServico
     */
    public JFCargo() {
        initComponents();
    }

    public JFCargo(Conexao cx) {
        initComponents();
        this.cx = cx;
        crn     = new CargoRN(cx);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExcluir = new javax.swing.JButton();
        bAtualizar = new javax.swing.JButton();
        bInserir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bProcurar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tSalario = new javax.swing.JTextField();
        bSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        bAtualizar.setText("Atualizar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        bInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/inserir.jpg"))); // NOI18N
        bInserir.setText("Inserir");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(0).setMinWidth(60);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getColumnModel().getColumn(0).setMaxWidth(60);

        bProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/procurar.jpg"))); // NOI18N
        bProcurar.setToolTipText("Procurar informações");
        bProcurar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcurarActionPerformed(evt);
            }
        });

        jLabel2.setText("Salário");

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/sair.jpg"))); // NOI18N
        bSair.setToolTipText("Sair");
        bSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bInserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(bProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bInserir)
                        .addComponent(bProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        cargo = new Cargo();
        setaObjeto();
        msg   = crn.inserirObjeto(cargo);
        if(msg == null || msg.isEmpty()){
            msg = "Sucesso ao realizar operação";
        }
        if(msg != null && !msg.isEmpty()){
            qtd++;
            obj.add(cargo);
            showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_bInserirActionPerformed

    private void bProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcurarActionPerformed
        this.setCursor(getPredefinedCursor(Cursor.WAIT_CURSOR));
        Thread tprocurar = new Thread(new Runnable() {
            @Override
            public void run() {
                obj = crn.procuraLista("nome", tNome.getText(), "parcial");
                if(obj != null && !obj.isEmpty()){
                    qtd = obj.size();
                    listar();
                }else{
                    showMessageDialog(null, "Nada encontrado");
                }
            }
        });
        tprocurar.start();
        this.setCursor(getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bProcurarActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        setaObjeto();
        msg   = crn.atualizarObjeto(cargo);
        if(msg == null || msg.isEmpty()){
            msg = "Sucesso ao realizar operação";
        }
        if(msg != null && !msg.isEmpty()){
            for(int i = 0; i < obj.size(); i++){
                if(obj.get(i).getCodigo() == cargo.getCodigo()){
                    obj.set(i, cargo);
                    listar();
                    break;
                }
            }
            showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        setaObjeto();
        msg   = crn.excluirObjeto(cargo);
        if(msg == null || msg.isEmpty()){
            msg = "Sucesso ao realizar operação";
        }
        if(msg != null && !msg.isEmpty()){
            obj.remove(cargo);
            qtd--;
            listar();
            showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_bExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        cargo = obj.get(tabela.getSelectedRow());
        setaTela();
    }//GEN-LAST:event_tabelaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela.getColumnModel().getColumn(0).setPreferredWidth((int) (tabela.getWidth() * 0.2));
        tabela.getColumnModel().getColumn(1).setPreferredWidth((int) (tabela.getWidth() * 0.8));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            showMessageDialog(null, "Erro causado por:\n" +  ex);
        }
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new JFCargo().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bInserir;
    private javax.swing.JButton bProcurar;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tSalario;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

   /**lista tudo o que está na tabela**/  
    private void listar() {
            if(tabela.getRowCount() > 0){
                tm.limpar();
            }
            tm.addLista(obj);  
    } 

    private void setaObjeto() {
        cargo.setNome(tNome.getText());
    }

    private void setaTela() {
        tNome.setText(cargo.getNome());
    }
}
