/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import static java.awt.Cursor.getPredefinedCursor;
import static java.awt.EventQueue.invokeLater;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import org.alfredlibrary.utilitarios.clima.Clima;
import org.alfredlibrary.utilitarios.clima.climatempo.Climatempo;
import persistencia.Conexao;
import visao.recursos.utilitarios.Codificacao;
import visao.recursos.utilitarios.TableModel;
import visao.recursos.utilitarios.Validacao;

/**
 *
 * @author ThyagoHenrique
 */
public class JFClima extends javax.swing.JFrame {
      private static final long serialVersionUID = 1L;

     Collection<Clima>  climas;
     String             titulo[]  = new String[]{"Data", "Descrição", "Min", "Máx."};
     TableModel         tm        = new TableModel(titulo, 1, titulo.length);
     String             msg       = "";
     String             codigo    = "";
     Conexao            cx;
     Validacao          validacao = new Validacao();
     Codificacao        codifica  = new Codificacao();
    /**
     * Creates new form JFServico
     */
    public JFClima() {
        initComponents();
        tabela.setModel(tm);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bProcurar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        ccidade = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clima");

        jLabel1.setText("Nome");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Descrição", "Máx", "Min"
            }
        ));
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(0).setMinWidth(60);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getColumnModel().getColumn(0).setMaxWidth(60);

        bProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/procurar.jpg"))); // NOI18N
        bProcurar.setToolTipText("Procurar informações");
        bProcurar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcurarActionPerformed(evt);
            }
        });

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/sair.jpg"))); // NOI18N
        bSair.setToolTipText("Sair");
        bSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ccidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ponta Grossa", "Curitiba", "Castro", "São Paulo", "Porto Alegre" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ccidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcurarActionPerformed
        this.setCursor(getPredefinedCursor(Cursor.WAIT_CURSOR));
        Thread tprocurar = new Thread(() -> {
            if(ccidade.getSelectedItem().equals("Ponta Grossa")){
                codigo = "279";
            }
            if(ccidade.getSelectedItem().equals("Curitiba")){
                codigo = "271";
            }
            if(ccidade.getSelectedItem().equals("Castro")){
                codigo = "269";
            }  
            if(ccidade.getSelectedItem().equals("São Paulo")){
                codigo = "558";
            } 
            if(ccidade.getSelectedItem().equals("Porto Alegre")){
                codigo = "363";
            }  
            climas = obterClima(codigo);
            if(climas != null && !climas.isEmpty()){
                listar();
            }        
        });
        tprocurar.start();
        this.setCursor(getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bProcurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            showMessageDialog(null, "Erro causado por:\n" +  ex);
        }
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new JFClima().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bProcurar;
    private javax.swing.JButton bSair;
    private javax.swing.JComboBox ccidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

   /**lista tudo o que está na tabela**/  
    private void listar() {
        Thread tlistar = new Thread(() -> {
            tabela.setModel(new TableModel(titulo, climas.size(), titulo.length));
            int i = 0;
            for (Clima c : obterClima(codigo)) {
                    tabela.setValueAt(validacao.mascaraData("dd/MM/yyyy", c.getData()), i, 0);
                    tabela.setValueAt(codifica.encode(c.getFrase()), i, 1);
                    tabela.setValueAt(c.getMaxima(), i, 2);
                    tabela.setValueAt(c.getMinima(), i, 3);
                    i++;
            }
            tabela.setAutoCreateRowSorter(true);        
        });
        tlistar.start();
    } 
    
    public Collection<Clima> obterClima(String codigo) {  
        climas = Climatempo.obterClima (codigo); 
        return Collections.unmodifiableCollection(climas);
    }        
}
