/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import static java.awt.Cursor.getPredefinedCursor;
import static java.awt.EventQueue.invokeLater;
import java.util.ArrayList;
import java.util.List;
import static java.util.logging.Logger.getLogger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import negocio.PessoaRN;
import persistencia.Conexao;
import visao.tabelas.TableModelPessoa;
import vo.Pessoa;

/**
 *
 * @author Thyago
 */
public class JFConsultaPessoa extends JDialog {
    private static final long serialVersionUID = 1L;

    Conexao             cx;
    boolean             okSelecionado   = false;
    PessoaRN            prn;
    List<Pessoa>        obj             = new ArrayList<>(100);
    TableModelPessoa    tm              = new TableModelPessoa(); 
    Pessoa              pessoa          = new Pessoa();
    /**
     * Creates new form JFConsultaPessoa
     */
    public JFConsultaPessoa() {
        initComponents();
    }

    public JFConsultaPessoa(Conexao cx) {
        initComponents();
        tabela.setModel(tm);
        this.cx = cx;
        prn     = new PessoaRN(cx);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tnome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bperfil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tcodigo = new javax.swing.JTextField();
        bMalaDireta = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de pessoas");

        jLabel1.setText("Nome");

        tnome.setToolTipText("Aperte enter para pesquisar");
        tnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnomeKeyPressed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(0).setMinWidth(50);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(0).setMaxWidth(50);

        bperfil.setText("Perfil pessoa");
        bperfil.setToolTipText("Retorna para a tela de perfil da pessoa");
        bperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperfilActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        tcodigo.setToolTipText("Aperte enter para pesquisar");
        tcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcodigoKeyPressed(evt);
            }
        });

        bMalaDireta.setText("Mala Direta");
        bMalaDireta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMalaDiretaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bMalaDireta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bperfil))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bperfil)
                    .addComponent(bMalaDireta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        pessoa = obj.get(tabela.getSelectedRow());
    }//GEN-LAST:event_tabelaMouseClicked

    private void bperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperfilActionPerformed
       okSelecionado = true; //Dizemos que o ok foi selecionado.
       setVisible(false);
    }//GEN-LAST:event_bperfilActionPerformed

    private void tcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcodigoKeyPressed
        if(evt.getKeyCode() == 10){
            pessoa = prn.procurarObjeto("codigo", (tcodigo.getText()));
            if(pessoa != null && pessoa.getNome() != null){
                obj.add(pessoa);
                listar();
            }            
        }
    }//GEN-LAST:event_tcodigoKeyPressed

    private void tnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnomeKeyPressed
        if(evt.getKeyCode() == 10){
            this.setCursor(getPredefinedCursor(Cursor.WAIT_CURSOR));
            Thread tprocurar = new Thread(() -> {
                obj = prn.procuraLista("nome", tnome.getText(), "parcial");
                if(obj != null && !obj.isEmpty()){
                    listar();
                }else{
                    showMessageDialog(null, "Nada encontrado");
                }           
            });
            tprocurar.start();
            this.setCursor(getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_tnomeKeyPressed

    private void bMalaDiretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMalaDiretaActionPerformed
        if(obj != null && !obj.isEmpty()){
            new JFMalaDireta(obj, cx).setVisible(true);
        }else{
            showMessageDialog(null, "Nada selecionado", "Erro:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bMalaDiretaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Metal (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(JFConsultaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFConsultaPessoa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMalaDireta;
    private javax.swing.JButton bperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tcodigo;
    private javax.swing.JTextField tnome;
    // End of variables declaration//GEN-END:variables

    public boolean alterarDadosPessoa(){  
        setModal(true);         //A dialog tem que ser modal. So pode retornar do setVisible apos ficar invis�vel.
        setVisible(true);       
        return okSelecionado;   //Retornamos true, se ele pressionou ok.
    }      
    
   /**lista tudo o que está na tabela**/  
    private void listar() {
            if(tabela.getRowCount() > 0){
                tm.limpar();
            }
            tm.addLista(obj);
    }       

}
