/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.List;
import static java.util.logging.Logger.getLogger;
import javax.swing.JOptionPane;
import static javax.swing.SwingUtilities.invokeLater;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import persistencia.Conexao;
import visao.recursos.utilitarios.Email;
import vo.Pessoa;

/**
 *
 * @author ThyagoHenrique
 */
public class JFMalaDireta extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    Conexao         cx;
    Email           email = new Email();
    String          msg   = "";
    List<Pessoa>    obj; 
    /**
     * Creates new form JFEmail
     */
    public JFMalaDireta() {
        initComponents();
        this.setSize(500, 500);
    }
    
    public JFMalaDireta(List<Pessoa> obj, Conexao cx) {
        initComponents();
        this.setSize(500, 500);
        this.cx  = cx;
        this.obj = obj;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tAssunto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMensagem = new javax.swing.JEditorPane();
        bSair = new javax.swing.JButton();
        bEnvia = new javax.swing.JButton();
        pBarra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mala Direta");
        setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel2.setText("Assunto");

        jLabel3.setText("Mensagem");

        jScrollPane1.setViewportView(tMensagem);

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/sair.jpg"))); // NOI18N
        bSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        bEnvia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/enviar_email.jpg"))); // NOI18N
        bEnvia.setText("Enviar");
        bEnvia.setToolTipText("Enviar a mensagem");
        bEnvia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bEnvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(bEnvia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSair)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAssunto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEnvia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bSair, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(pBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviaActionPerformed
        pBarra.setMaximum(obj.size());
        if(tAssunto.getText() != null && !tAssunto.getText().isEmpty() && 
           tMensagem.getText() != null && !tMensagem.getText().isEmpty()){
            for (Pessoa p : obj) {
                msg = email.sendMail(null, p.getEmail(), tAssunto.getText(), tMensagem.getText());
                if(msg != null && !msg.isEmpty()){
                    JOptionPane.showMessageDialog(null, msg, "ERRO na mensagem:", JOptionPane.ERROR_MESSAGE);
                    break;
                }else{
                    pBarra.setValue(pBarra.getValue() + 1);
                }               
            }
            if(msg != null && !msg.isEmpty()){
                JOptionPane.showMessageDialog(null, "Enviado com sucesso a mala direta");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Faltou preencher algum campo na mensagem, por favor verifique!", "ERRO na mensagem:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEnviaActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        dispose();
    }//GEN-LAST:event_bSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(JFMalaDireta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFMalaDireta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnvia;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pBarra;
    private javax.swing.JTextField tAssunto;
    private javax.swing.JEditorPane tMensagem;
    // End of variables declaration//GEN-END:variables
}
