/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import static java.awt.Cursor.getPredefinedCursor;
import static java.awt.EventQueue.invokeLater;
import java.awt.HeadlessException;
import java.util.Collection;
import static java.util.logging.Logger.getLogger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import static org.alfredlibrary.utilitarios.correios.Rastreamento.rastrear;
import org.alfredlibrary.utilitarios.correios.RegistroRastreamento;
import visao.recursos.utilitarios.TableModel;

/**
 *
 * @author ThyagoHenrique
 */
public class JFRastreamentoCorreios extends javax.swing.JFrame {
     private static final long serialVersionUID = 1L;

     Collection<RegistroRastreamento> colRegistoRastreamento;
     String                           titulo[]               = new String[]{"Local", "Data", "Detalhe", "Ação"};
     TableModel                       tm                     = new TableModel(titulo, 1, titulo.length);    
    /**
     * Creates new form JFRastreamentoCorreios
     */
    public JFRastreamentoCorreios() {
        initComponents();
        tabela.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rastreamentos dos correios");

        jButton1.setText("Sair");

        jButton2.setText("Procurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Local", "Data", "Hora", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCodigo)
                            .addComponent(jButton2)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setCursor(getPredefinedCursor(Cursor.WAIT_CURSOR));
        Thread tprocurar = new Thread(() -> {
            if(tCodigo.getText() != null && !tCodigo.getText().isEmpty()){
                try{
                    colRegistoRastreamento = rastrear(tCodigo.getText()); 
                    if(colRegistoRastreamento.size() > 0){
                        listar();
                    }else{
                        showMessageDialog(null, "Nada encontrado", "ERRO:", JOptionPane.INFORMATION_MESSAGE);
                    }
                }catch(HeadlessException ex){
                    showMessageDialog(null, ex, "ERRO:", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                showMessageDialog(null, "Não pode pesquisar em branco", "ERRO:", JOptionPane.INFORMATION_MESSAGE);
            }        
        });
        this.setCursor(getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        tprocurar.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(JFRastreamentoCorreios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new JFRastreamentoCorreios().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

   /**lista tudo o que está na tabela**/  
    private void listar() {
        Thread tlistar = new Thread(() -> {
            int i = 0;
            tabela.setModel(new TableModel(titulo, colRegistoRastreamento.size(), titulo.length));
            for (RegistroRastreamento rr : colRegistoRastreamento) {             
                tabela.setValueAt(rr.getLocal(), i, 0);
                if(rr.getDataHora() != null){
                    tabela.setValueAt(rr.getDataHora(), i, 1);
                }else{
                    tabela.setValueAt("Sem data", i, 1);
                }
                if(rr.getDetalhe() != null && !rr.getDetalhe().isEmpty()){
                    tabela.setValueAt(rr.getDetalhe(), i, 2);  
                }else{
                    tabela.setValueAt("Sem detalhes", i, 2);  
                }
                if(rr.getAcao() != null && !rr.getAcao().isEmpty()){
                    tabela.setValueAt(rr.getAcao(), i, 3);  
                }else{
                    tabela.setValueAt("Sem ação", i, 3); 
                }
                i++;
            }
            tabela.setAutoCreateRowSorter(true);            
    });
    tlistar.start();
    } 
}
