/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import static java.awt.Cursor.getPredefinedCursor;
import static java.awt.EventQueue.invokeLater;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import negocio.ServicoRN;
import persistencia.Conexao;
import visao.tabelas.TableModelServico;
import vo.Servico;

/**
 *
 * @author ThyagoHenrique
 */
public class JFServico extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    List<Servico>     obj         = new ArrayList<>(50);
    ServicoRN         srn;
    Servico           servico     = new Servico();
    Conexao           cx;
    TableModelServico tm          = new TableModelServico(); 
    /**
     * Creates new form JFServico
     */
    public JFServico() {
        initComponents();
    }

    public JFServico(Conexao cx) {
        initComponents();
        this.cx = cx;
        srn     = new ServicoRN(cx);
        tabela.setModel(tm);
    }    
    
    public JFServico(Conexao cx, Servico servico, List<Servico> obj) {
        initComponents();
        this.cx         = cx;
        srn             = new ServicoRN(cx);
        this.obj        = obj;
        this.servico    = servico;
        if(servico != null && servico.getNome() != null){
            setaTela();
        }
        tabela.setModel(tm);
        if(obj != null && !obj.isEmpty()){
            listar();
        }
    }      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSair = new javax.swing.JButton();
        bexcluir = new javax.swing.JButton();
        batualizar = new javax.swing.JButton();
        binserir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bProcurarServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de serviços");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/sair.jpg"))); // NOI18N
        bSair.setToolTipText("Fechar janela");
        bSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        bexcluir.setText("Excluir");
        bexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexcluirActionPerformed(evt);
            }
        });

        batualizar.setText("Atualizar");
        batualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batualizarActionPerformed(evt);
            }
        });

        binserir.setText("Inserir");
        binserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binserirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(0).setMinWidth(60);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getColumnModel().getColumn(0).setMaxWidth(60);

        bProcurarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/recursos/imagens/procurar.jpg"))); // NOI18N
        bProcurarServico.setToolTipText("Procurar Informações");
        bProcurarServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bProcurarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcurarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(binserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bexcluir)
                        .addGap(37, 37, 37)
                        .addComponent(bProcurarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bSair)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(binserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bProcurarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(95, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        dispose();
    }//GEN-LAST:event_bSairActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        servico = obj.get(tabela.getSelectedRow());
        setaTela();
    }//GEN-LAST:event_tabelaMouseClicked

    private void binserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserirActionPerformed
        servico    = new Servico();
        setaObjeto();
        String msg = srn.inserirObjeto(servico);
        if(msg != null && !msg.isEmpty()){
            showMessageDialog(null, msg);
        }else{
            showMessageDialog(null, "Inserido com sucesso");
        }
    }//GEN-LAST:event_binserirActionPerformed

    private void batualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batualizarActionPerformed
        setaObjeto();
        String msg = srn.atualizarObjeto(servico);
        if(msg != null && !msg.isEmpty()){
            showMessageDialog(null, msg);
        }else{
            showMessageDialog(null, "Atualizado com sucesso");
        }
    }//GEN-LAST:event_batualizarActionPerformed

    private void bexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluirActionPerformed
        servico    = new Servico();
        setaObjeto();
        String msg = srn.excluirObjeto(servico);
        if(msg != null && !msg.isEmpty()){
            showMessageDialog(null, msg);
        }else{
            showMessageDialog(null, "Excluido com sucesso");
        }
    }//GEN-LAST:event_bexcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Thread tcomeco = new Thread(new Runnable() {
            @Override
            public void run() {
                tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                tabela.getColumnModel().getColumn(0).setPreferredWidth((int) (tabela.getWidth() * 0.2));
                tabela.getColumnModel().getColumn(1).setPreferredWidth((int) (tabela.getWidth() * 0.8));
            }
        });
        tcomeco.start();
    }//GEN-LAST:event_formWindowOpened

    private void bProcurarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcurarServicoActionPerformed
        this.setCursor(getPredefinedCursor(Cursor.WAIT_CURSOR));
        servico = srn.procurarObjeto("nome", "");
        if(servico != null){
            setaTela();
        }
        this.setCursor(getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bProcurarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            showMessageDialog(null, "Erro causado por:\n" +  ex);
        }
        //</editor-fold>

        /* Create and display the form */
        invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFServico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bProcurarServico;
    private javax.swing.JButton bSair;
    private javax.swing.JButton batualizar;
    private javax.swing.JButton bexcluir;
    private javax.swing.JButton binserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    private void listar() {
            if(tabela.getRowCount() > 0){
                tm.limpar();
            }
            tm.addLista(obj);
    } 

    private void setaTela() {
        jTextField1.setText(servico.getNome());
    }
    
    private void setaObjeto(){
        servico.setNome(jTextField1.getText());
    }
}
